# Generated by Django 5.1 on 2025-05-12 21:20
import base64

from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):
    def create_initial_user(apps, schema_editor):
        User = apps.get_model("account", "User")
        User.objects.create(
            email="admin@gmail.com",
            cellphone="00000000000",
            password=make_password(base64.b64decode("VHdJdTdhbjQzQHYx".encode()).decode()),
            name="admin",
            is_superuser=True,
            is_staff=True,
            is_active=True,
        )

    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.RunPython(create_initial_user),
    ]
