# Generated by Django 5.2.1 on 2026-05-17 02:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cellphone', models.CharField(db_index=True, error_messages={'unique': 'Esse numéro de celular já está sendo usado por outro usuário!'}, max_length=64, null=True)),
                ('password', models.CharField(max_length=104)),
                ('name', models.CharField(max_length=256, null=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Esse e-mail já está sendo usado por outro usuário!'}, max_length=256, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('avatar', models.TextField(max_length=100, null=True)),
                ('file_name', models.CharField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
