# Generated by Django 5.2.1 on 2026-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(blank=True, choices=[('ELEITOR', 'Eleitor'), ('CANDIDATO', 'Candidato')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ELEITOR', 'Eleitor'), ('CANDIDATO', 'Candidato')], max_length=10, null=True),
        ),
    ]
