# Generated by Django 4.2.5 on 2023-10-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'Esse e-mail já foi cadastrado'}, max_length=256, null=True, unique=True),
        ),
    ]
