# Generated by Django 5.2.1 on 2025-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
