# Generated by Django 5.2.1 on 2025-08-03 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_candidate_avatar_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="avatar",
        ),
    ]
