# Generated by Django 4.2.5 on 2023-10-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinguser',
            name='plate',
            field=models.ForeignKey(db_column='id_plate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.plate'),
        ),
        migrations.AlterUniqueTogether(
            name='votinguser',
            unique_together={('user', 'plate')},
        ),
    ]
