# Generated by Django 4.2.5 on 2023-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_votinguser_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.CharField(max_length=54, unique=True, verbose_name='Description'),
        ),
    ]
