# Generated by Django 5.2.1 on 2026-05-17 04:13

import core.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalcandidate_historicaleventvoting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='historicalcandidate',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.models.upload_to),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
