# Generated by Django 4.2.5 on 2023-10-07 18:13
from django.db import migrations, models
import django.contrib.postgres.fields.citext


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_user_cellphone_alter_voting_description'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS citext;"),
    ]
