# Generated by Django 4.2.5 on 2023-10-08 20:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_extension_citext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=core.models.CITextField(max_length=54, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Esse e-mail já foi cadastrado'}, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=core.models.CITextField(max_length=54, unique=True, verbose_name='Description'),
        ),
    ]
