# Generated by Django 4.2.5 on 2023-10-09 20:37
import base64

import core.models
from django.db import migrations, models
from core.models import User


class Migration(migrations.Migration):



    dependencies = [
        ('core', '0006_alter_plate_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=core.models.CITextField(error_messages={'unique': 'Já existe uma chapa cadastrada com o mesmo nome!'}, max_length=54, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(error_messages={'unique': 'Esse numéro de celular já está sendo usado por outro usuário!'}, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Esse e-mail já está sendo usado por outro usuário!'}, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=core.models.CITextField(error_messages={'unique': 'Já existe uma votação cadastrada com o mesmo nome!'}, max_length=54, unique=True, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='votinguser',
            unique_together={('user', 'voting')},
        ),
    ]
