# Generated by Django 4.2.5 on 2023-10-11 00:23

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_plate_name_alter_user_cellphone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('cellphone', models.CharField(error_messages={'unique': 'Esse numéro de celular já está sendo usado por outro usuário!'}, max_length=64, null=True, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to=core.models.upload_to)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='EventVoting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('description', core.models.CITextField(error_messages={'unique': 'Já existe uma votação cadastrada com o mesmo nome!'}, max_length=54, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'event_voting',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('cellphone', models.CharField(error_messages={'unique': 'Esse numéro de celular já está sendo usado por outro usuário!'}, max_length=64, null=True, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to=core.models.upload_to)),
            ],
            options={
                'db_table': 'voter',
            },
        ),
        migrations.AlterField(
            model_name='plate',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='plateuser',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='votingplate',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='ResumeVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('plate', models.ForeignKey(db_column='id_plate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.plate')),
                ('voting', models.ForeignKey(db_column='id_voting', on_delete=django.db.models.deletion.DO_NOTHING, to='core.eventvoting')),
            ],
            options={
                'db_table': 'resume_vote',
            },
        ),
        migrations.AlterUniqueTogether(
            name='plateuser',
            unique_together={('plate', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='votinguser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plateuser',
            name='candidate',
            field=models.ForeignKey(db_column='id_candidate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='votinguser',
            name='voter',
            field=models.ForeignKey(db_column='id_voter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.voter'),
        ),
        migrations.AlterField(
            model_name='votingplate',
            name='voting',
            field=models.ForeignKey(db_column='id_voting', on_delete=django.db.models.deletion.DO_NOTHING, to='core.eventvoting'),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='voting',
            field=models.ForeignKey(db_column='id_voting', on_delete=django.db.models.deletion.DO_NOTHING, to='core.eventvoting'),
        ),
        migrations.AlterUniqueTogether(
            name='plateuser',
            unique_together={('candidate', 'plate'), ('plate', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='votinguser',
            unique_together={('voter', 'voting')},
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
        migrations.RemoveField(
            model_name='plateuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votinguser',
            name='user',
        ),
    ]
