# Generated by Django 4.2.5 on 2023-10-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidate_eventvoting_voter_alter_plate_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='disabled',
            field=models.BooleanField(db_column='disabled', default=False),
        ),
        migrations.AddField(
            model_name='resumevote',
            name='quantity',
            field=models.IntegerField(blank=True, db_column='quantity_vote', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resumevote',
            name='voting',
            field=models.ForeignKey(db_column='id_voting', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.eventvoting'),
        ),
    ]
