# Generated by Django 4.2.5 on 2023-10-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidate_disabled_resumevote_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinguser',
            name='plate',
            field=models.ForeignKey(db_column='id_plate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voting_user_plate', to='core.plate'),
        ),
    ]
