# Generated by Django 4.2.5 on 2023-10-18 16:41
from core.models import User
import base64
from django.db import migrations, models


class Migration(migrations.Migration):

    def create_initial_user(apps, schema_editor):
        User.objects.create_superuser(
            email='admin@gmail.com',
            cellphone='00000000000',
            password=base64.b64decode('VHdJdTdhbjQzQHYx'.encode()).decode(),
            name='admin',
        )

    dependencies = [
        ('core', '0010_alter_votinguser_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_permission',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunPython(create_initial_user),
    ]
