# Generated by Django 4.2.5 on 2023-10-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_has_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plateuser',
            unique_together={('plate', 'type')},
        ),
    ]
