# Generated by Django 4.2.5 on 2023-10-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_plateuser_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_permission',
        ),
    ]
