# Generated by Django 5.1 on 2025-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_has_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvoting',
            name='description',
            field=models.CharField(error_messages={'unique': 'Já existe uma votação cadastrada com o mesmo nome!'}, max_length=54, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(error_messages={'unique': 'Já existe uma chapa cadastrada com o mesmo nome!'}, max_length=54, unique=True),
        ),
    ]
