version: "3.8"

services:
  postgres:
    image: postgres:17
    hostname: postgres-votup
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=votup
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    hostname: votup
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=miniovotup
      - MINIO_ROOT_PASSWORD=miniovotup
    command: server --console-address ":9001" /data
    restart: always
    volumes:
      - minio_storage:/data

  minio-mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set votup http://minio:9000 miniovotup miniovotup;
        mc mb votup/votup;
        mc policy set public votup/votup;
      "
    restart: on-failure

volumes:
  db-data:
  minio_storage:
